project:
  type: website
  output-dir: docs

metadata-files:
  - _variables.yml

website:
  page-navigation: true
  title: "data science for openwashdata"
  description: "Website for data science for openwashdata course 002"
  site-url: "https://ds4owd-002.github.io/website/"
  repo-url: "https://github.com/ds4owd-002"
  favicon: "img/OWD-logo-18.png"
  search: false
  page-footer: 
    left: | 
        This course is part of the [openwashdata project](https://openwashdata.org/) supported by the 
        [Open Research Data Program of the ETH Board](https://ethrat.ch/en/eth-domain/open-research-data/)
    right:
      - text: Code of Conduct
        href: code_of_conduct.qmd
      - icon: "envelope-at"
        href: "mailto:ghe@mavt.ethz.ch?subject=ds4owd support"
        aria-label: Email
      - icon: github
        href: https://github.com/ds4owd-002
        aria-label: GitHub
      - icon: chat-left-dots
        href: https://matrix.to/#/#openwashdata-lobby:staffchat.ethz.ch
        aria-label: Matrix
  
  sidebar:
    background: "#C8CEF3"
    logo: "img/OWD-logo-20.png"
    logo-alt: "openwashdata logo."
    pinned: true
    align: center
    style: "docked"
    search: true
    collapse-level: 1
    tools:
      - icon: github
        href: https://github.com/ds4owd-002
        text: "GitHub organization"
    contents: 
      - href: index.qmd
        text: Course Overview
      - href: calendar.qmd
        text: Course Calendar
      - href: guide/index.qmd
        text: Guide
      - text: "---"
      - section: "Module 01"
        href: modules/md-01.qmd
        contents:
          - href: assignments/md-01/am-01-1-posit.qmd
            text: "am-01: Posit Cloud"
          - href: assignments/md-01/am-01-2-element.qmd
            text: "am-02: Element"
          - href: assignments/md-01/am-01-3-github.qmd
            text: "am-03: GitHub"
      - section: "Module 02"
        href: modules/md-02.qmd
        contents:
          - href: assignments/md-02/am-02-1-data-visualisation.qmd
            text: "am-01: Data visualization"
      - section: "Module 03"
        href: modules/md-03.qmd
        contents:
          - href: assignments/md-03/am-03-1-data-transformation.qmd
            text: "am-01: Data transformation"
          - href: assignments/md-03/am-03-2-spreadsheet.qmd
            text: "am-02: Spreadsheet"
      - section: "Module 04"
        href: modules/md-04.qmd
        contents:
          - href: assignments/md-04/am-04-1-reading.qmd
            text: "am-01: Data organization"
      - section: "Module 05"
        href: modules/md-05.qmd
        contents:
          - href: assignments/md-05/am-05-1-project-data.qmd
            text: "am-01: Project data"
      - section: "Module 06"
        href: modules/md-06.qmd
        contents:
          - href: assignments/md-06/am-06-1-reading.qmd
            text: "am-01: Good enough practices"
          - href: assignments/md-05/am-05-1-project-data.qmd
            text: "am-02: Project data"
      - section: "Module 07"
        href: modules/md-07.qmd
        contents:
          - href: assignments/md-07/am-07-1-pivoting.qmd
            text: "am-01: Pivot data"
          - href: assignments/md-07/am-07-2-project-metadata.qmd
            text: "am-02: Capstone project"
      - href: modules/md-08.qmd
        text: Module 08
      - href: modules/md-09.qmd
        text: Module 09
      - text: "---"
      - href: project/index.qmd
        text: "Capstone project"
format:
  html:
    theme:
      light: [litera, theme.scss]
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true
    mainfont: "Atkinson Hyperlegible"
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px
    include-in-header: 
        - text: |
            <script defer data-domain="ds4owd-002.github.io/website" src="https://plausible.io/js/script.js"></script>

execute: 
  freeze: auto

